# Generated by Django 2.2.6 on 2019-12-17 18:07

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('slug', models.SlugField(max_length=254, primary_key=True, serialize=False, unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=254, verbose_name='Nome')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('slug', models.SlugField(max_length=254, primary_key=True, serialize=False, unique=True, verbose_name='slug')),
                ('title', models.CharField(max_length=254, verbose_name='Título')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Conteúdo')),
                ('publish', models.BooleanField(default=False, verbose_name='Publicar?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
